### ISSUE TITLE
Re-consider Xcode build process

### ISSUE THREAD

**Issue by stv0g** [xhyve-xyz/xhyve#5]
I am not a huge fan of the Xcode project build which has been added in aadbaa8475f006d92682aeebc3231cf9a639ae67.

In my opinion, xhyve biggest plus is its lightweight add small codebase.
We should aim to maintain this and not become bloated like QEmu, Virtualbox etc.
Because if not, whats our differentiating factor?

I personally have no Xcode installed on my system.
And after some googling it seems possible to use Xcode with traditional Makefile projects.

So, whats the advantage of using Xcode in the build process? I would favor keeping the Makefile and removing the Xcode files or at least, moving them to another branch.

What do you think?

PS: The same is true of dependencies like libvdisk, lib9p etc... Lets try to keep everything optional.
A simple `git clone && make` should be enough to get started.

**Comment by jeremyhu** [comment]
Using Xcode as a build system does not cause a project to be bloated.  You can just as easily have a very large and bloated system based entirely on Makefiles.

The Makefile build system is still there and is useful for those that really want to use it (mainly useful for crosscompiling), and the Xcode build system is useful for those that prefer it.

The main advantage of using Xcode as a build system option is that it allows us to better integrate into other projects (either in a larger workspace, or in packaging environments / distributions).   Think of how easy it is to write recipes, portfiles, ebuilds, etc for autoconf or cmake projects compared to the bloat and maintenance nightmare associated with Makefile-based.  Furthermore, it allows us to possibly leverage Xcode's unit testing functionality and integrate with hosted CI and testing suites that rely on said standards.  Using handrolled makefiles is a non-starter for that infrastructure.

'git clone && make' is still enough to get started currently.  So is 'git clone && xcodebuild'.
